apiVersion: v1
kind: ConfigMap
metadata:
  namespace: kubeedge
  name: plugins
data:
  plugins.yaml: |
    plugins:
      # GitHub org
      kubeedge:
        plugins:
        - approve
        - assign
        - blunderbuss
        - cat
        - dog
        - help
        - heart
        - hold
        - invalidcommitmsg
        - label
        - lgtm
        # Close, reopen, flag and/or unflag an issue or PR as frozen/stale/rotten
        - lifecycle
        - mergecommitblocker
        - milestone
        - retitle
        - size
        - trigger
        - verify-owners
        - welcome
        - wip
        - yuks
      kubeedge:
        plugins:
        - release-note
    # approve specifies configuration for the approve plugin.
    approve:
    - repos:
      # GitHub Org name, means all repos under this organization using the same configuration.
      - kubeedge
      # require_self_approval requires PR authors to explicitly approve their PRs.
      require_self_approval: true

    triggers:
    - repos:
      # GitHub Org name, means all repos under this organization using the same configuration.
      - kubeedge
      # enables workflows run by github to be triggered by prow.
      trigger_github_workflows: true

    external_plugins:
      kubeedge:
      - name: cherrypicker
        events:
          - pull_request
          - issue_comment
    label:
      additional_labels:
        # These labels are used to make Tide merge with a non-default merge method
        - tide/merge-method-merge
        - tide/merge-method-rebase
        - tide/merge-method-squash
        - area/ads
        - ara/workload
        - area/bpf
